runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bower_components
  static_dir: bower_components
  secure: always
- url: /.*
  script: broker.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
